version: '3.4'

services:
  filptube.api:
    image: ${DOCKER_REGISTRY-}video-streaming
    build:
      context: .
      dockerfile: src/FilpTube.API/Dockerfile

  filptube.videostorage:
    image: ${DOCKER_REGISTRY-}filptubevideostorage
    build:
      context: .
      dockerfile: src/FilpTube.VideoStorage/Dockerfile

