version: '3.4'

services:
  video-streaming:
    image: video-streaming
    build:
      context: .
      dockerfile: src/FilpTube.API/Dockerfile

  video-storage:
    image: video-storage
    build:
      context: .
      dockerfile: src/FilpTube.VideoStorage/Dockerfile

