version: '3.4'

services:
  video-streaming:
    image: video-streaming
    build:
      context: .
      dockerfile: src/FilpTube.API/Dockerfile

  video-storage:
    image: video-storage
    build:
      context: .
      dockerfile: src/FilpTube.VideoStorage/Dockerfile

  db:
    image: mongo
    container_name: db
    ports:
        - 27017:27017
    restart: always
  
  Nats:
    image: nats
    container_name: nats
    ports:
        - 4222:4222
    restart: always

  video-history:
    image: video-history
    build:
      context: .
      dockerfile: src/FilpTube.History/Dockerfile

