apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-storage
  namespace: default
  labels:
    app: filp-tube
spec:
  selector:
    matchLabels:
      app: filp-tube
      component: video-storage
  replicas: 1
  template:
    metadata:
      labels:
        app: filp-tube
        component: video-storage
    spec:
      containers:
        - name: filp-tube
          image: video-storage:1
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: digitalocean
                  key: AccessKey
            - name: AWS_SECRET
              valueFrom:
                secretKeyRef:
                  key: AccessSecret
                  name: digitalocean
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 100Mi
          ports:
            - containerPort: 80
              name: video-storage
      restartPolicy: Always

