apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-history
  namespace: default
  labels:
    app: filp-tube
    component: video-history
spec:
  selector:
    matchLabels:
      app: filp-tube
      component: video-history
  replicas: 1
  template:
    metadata:
      labels:
        app: filp-tube
        component: video-history
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: video-history
          image: satish860/video-history:1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: DOTNET_ENVIRONMENT
              value: Development
            - name: DBHOST
              value: mongodb://db:27017
            - name: DBNAME
              value: video-streaming
            - name: NATSHOST
              value: nats
          ports:
            - containerPort: 80
              name: video-history
      restartPolicy: Always
