apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming
  namespace: default
  labels:
    app: filp-tube
    component: video-streaming
spec:
  selector:
    matchLabels:
      app: filp-tube
      component: video-streaming
  replicas: 1
  template:
    metadata:
      labels:
        app: filp-tube
        component: video-streaming
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: video-streaming
          image: registry.digitalocean.com/bmdk/video-streaming:5
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: DBHOST
              value: mongodb://db:27017
            - name: VIDEOSTORAGE
              value: http://video-storage
            - name: DBNAME
              value: video-streaming
            - name: NATSHOST
              value: Nats
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - containerPort: 80
              name: video-streaming
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: video-streaming
  namespace: default
  labels:
    app: filp-tube
    component: video-streaming
spec:
  selector:
    app: filp-tube
    component: video-streaming
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: video-streaming
      protocol: TCP
      port: 8090
      targetPort: video-streaming
